updated create-bucket file

diff --git a/create-bucket b/create-bucket
--- a/create-bucket
+++ b/create-bucket
@@ -8,12 +8,25 @@ fi
 
 # pass the bucket name as a positional parameter
 bucket_name=$1
+region="us-west-2"
+
+
 
 # Check if the bucket exists
 if aws s3api head-bucket --bucket "$bucket_name" 2>/dev/null; then
     echo "Bucket $bucket_name already exists."
 else
-  # change the line below
-  echo $bucket_name
+    # change the line below
+    aws s3api create-bucket \
+      --bucket "$bucket_name" \
+      --region "$region" \
+      --create-bucket-configuration LocationConstraint="$region"
+
+    if [ $? -eq 0 ]; then
+        echo "Bucket $bucket_name created successfully."
+    else
+        echo "Failed to create bucket $bucket_name."
+    fi
+
 fi
 
